guest = []
guest.insert(0,"Eva")
guest.insert(1,"Jesus")
guest.insert(2,"Emmanuel")
print(guest[0] + ", you have been invited to my birthday party this Friday.")
print(guest[1] + ", you have been invited to my birthday party this Friday.")
print(guest[2] + ", you have been invited to my birthday party this Friday.\n")
print(guest[2] + " just informed me he won't be making it to my party.")
guest.remove("Emmanuel")
guest.append("Joshua")
print("\nNew invite list: \n")
print(guest[0] + ", you have been invited to my birthday party this Friday.")
print(guest[1] + ", you have been invited to my birthday party this Friday.")
print(guest[2] + ", you have been invited to my birthday party this Friday.\n")
