guest = []
guest.insert(0,"Eva")
guest.insert(1,"Jesus")
guest.insert(2,"Emmanuel")
print(guest[0] + ", you have been invited to my birthday party this Friday.")
print(guest[1] + ", you have been invited to my birthday party this Friday.")
print(guest[2] + ", you have been invited to my birthday party this Friday.")
print("\nGood news everyone! I was able to secure a bigger dinner table. :D\n")
guest.insert(0,"Jariel")
guest.insert(int(len(guest)/2),"Yrelis")
guest.append("Aida")
print("\nNew list of guests:\n")
print(guest[0] + ", you have been invited to my birthday party this Friday.")
print(guest[1] + ", you have been invited to my birthday party this Friday.")
print(guest[2] + ", you have been invited to my birthday party this Friday.")
print(guest[3] + ", you have been invited to my birthday party this Friday.")
print(guest[4] + ", you have been invited to my birthday party this Friday.")
print(guest[5] + ", you have been invited to my birthday party this Friday.")
