places = []
places.append("paris")
places.append("spain")
places.append("canada")
places.append("puerto rico")
places.append("dominican republic")
print("\nOriginal list:\n")
print(places)
print("\nSorted list:\n")
print(sorted(places))
print("\nOriginal list:")
print(places)
print("\nSorted in reverse:\n")
print(sorted(places,reverse=True))
print("\nOriginal list:\n")
print(places)
places.reverse()
print(places)
places.reverse()
print(places)
print("Here is the sorted list:\n")
places.sort()
print(places)
places.sort(reverse=True)
print("Here is the list sorted in reverse order:\n")
print(places)
