guest = []
guest.insert(0,"Eva")
guest.insert(1,"Jesus")
guest.insert(2,"Emmanuel")
print(guest[0] + ", you have been invited to my birthday party this Friday.")
print(guest[1] + ", you have been invited to my birthday party this Friday.")
print(guest[2] + ", you have been invited to my birthday party this Friday.")
print("\nGood news everyone! I was able to secure a bigger dinner table. :D\n")
guest.insert(0,"Jariel")
guest.insert(int(len(guest)/2),"Yrelis")
guest.append("Aida")
print("\nNew list of guests:\n")
print(guest[0] + ", you have been invited to my birthday party this Friday.")
print(guest[1] + ", you have been invited to my birthday party this Friday.")
print(guest[2] + ", you have been invited to my birthday party this Friday.")
print(guest[3] + ", you have been invited to my birthday party this Friday.")
print(guest[4] + ", you have been invited to my birthday party this Friday.")
print(guest[5] + ", you have been invited to my birthday party this Friday.")
print("\nI am so sorry to say, that I will only be able to invite two of you\nto my birthday party.")
guest1 = guest.pop()
guest2 = guest.pop()
guest3 = guest.pop()
guest4 = guest.pop()
print("I must apologize for the following, the list of people listed here won't\nbe able to attend the party:")
reject = guest1 + "," + guest2 + "," + guest3 + "," + guest4 + "."
print(reject)
print("Still invited are:")
print(guest[0])
print(guest[1])
del guest[1]
del guest[0]
print(guest)
